/** Short definitions shown on first use (dotted underline → popover). */
export const GLOSSARY: Record<string, { term: string; def: string }> = {
  wafer: { term: 'Wafer', def: 'A thin, polished disc of single-crystal silicon (here 300 mm across, about 0.78 mm thick) on which hundreds of chips are built at once.' },
  foup: { term: 'FOUP', def: 'Front-opening unified pod: a sealed plastic carrier that holds 25 wafers and keeps them in clean air between tools.' },
  cleanroom: { term: 'Cleanroom', def: 'A room with filtered, downward-flowing air, classed by how few particles it allows. Wafers are further protected inside sealed pods and tool enclosures.' },
  particle: { term: 'Particle', def: 'A speck of dust or debris. One smaller than a feature can still bridge or break a circuit.' },
  die: { term: 'Die', def: 'One chip on the wafer. All dies get the same process; after testing, the wafer is cut into separate dies.' },
  oxide: { term: 'Oxide', def: 'Silicon dioxide (SiO₂), glass, grown from the silicon itself or deposited. An excellent insulator.' },
  nitride: { term: 'Nitride', def: 'Silicon nitride, a hard insulator used here as a mask for etching and a stop for polishing.' },
  isolation: { term: 'Isolation', def: 'Oxide-filled trenches between transistors so current cannot leak from one to the next.' },
  lithography: { term: 'Lithography', def: 'Printing a pattern with light: a reticle image is projected onto light-sensitive resist, which is then developed into a stencil.' },
  etch: { term: 'Etch', def: 'Removing material where the resist leaves it exposed. A plasma etch cuts nearly straight down.' },
  cmp: { term: 'CMP', def: 'Chemical-mechanical planarisation: polishing the wafer flat with a rotating pad and a chemical slurry.' },
  doping: { term: 'Doping', def: 'Adding a small amount of another element to silicon to change how it conducts: phosphorus or arsenic make it n-type, boron makes it p-type.' },
  implant: { term: 'Implant', def: 'Firing accelerated dopant ions into the wafer. Resist or a gate blocks them where they should not go.' },
  well: { term: 'Well', def: 'A deep doped region of silicon: PMOS transistors sit in an n-well, NMOS transistors in a p-well.' },
  anneal: { term: 'Anneal', def: 'A controlled heating step that repairs implant damage and lets dopant atoms take their place in the crystal.' },
  gate: { term: 'Gate', def: 'The transistor’s control electrode. Its voltage, acting through a thin oxide, opens or closes a channel in the silicon beneath.' },
  polysilicon: { term: 'Polysilicon', def: 'Silicon made of many small crystals. Heavily doped, it conducts and serves as the gate electrode in this flow.' },
  resist: { term: 'Resist', def: 'Photoresist: a light-sensitive film. In a positive resist, exposed areas become soluble and wash away in the developer.' },
  reticle: { term: 'Reticle', def: 'The mask: a quartz plate carrying one layer’s pattern in chrome, 4× larger than it will print on the wafer.' },
  alignment: { term: 'Alignment', def: 'Before exposing, the scanner measures marks from earlier layers and corrects its stages so the new pattern lands on the old one.' },
  overlay: { term: 'Overlay', def: 'How accurately one layer sits on top of the previous one, measured after development.' },
  exposure: { term: 'Exposure', def: 'Shining patterned light onto the resist. It changes the resist’s chemistry, not the layers underneath.' },
  dose: { term: 'Dose', def: 'How much light energy the resist receives per area. It controls where the edges of the pattern land.' },
  latent: { term: 'Latent image', def: 'The invisible chemical pattern in exposed resist before it is developed.' },
  scanner: { term: 'Scanner', def: 'The exposure tool: it scans a slit of light across the reticle and wafer, then steps to the next field.' },
  peb: { term: 'Post-exposure bake', def: 'A bake after exposure that lets light-made acid switch chemically amplified resist to a soluble form.' },
  develop: { term: 'Develop', def: 'Washing the exposed wafer in developer. Positive resist dissolves where it was exposed.' },
  cd: { term: 'CD', def: 'Critical dimension: the measured width of the smallest, most important feature on a layer — here the gate line.' },
  rework: { term: 'Rework', def: 'Stripping a bad resist pattern and repeating the lithography. Possible only before the etch makes it permanent.' },
  selectivity: { term: 'Selectivity', def: 'How much faster an etch removes the target than the mask or the layer underneath.' },
  strip: { term: 'Strip', def: 'Removing the leftover resist after it has done its job, usually with an oxygen plasma and a wet clean.' },
  sourcedrain: { term: 'Source and drain', def: 'The heavily doped regions on either side of a gate. Current flows between them when the transistor is on.' },
  selfaligned: { term: 'Self-aligned', def: 'The gate itself masks the implant, so the source and drain end exactly at the gate edges.' },
  dielectric: { term: 'Dielectric', def: 'An insulating layer, such as oxide, that separates conductors.' },
  contact: { term: 'Contact', def: 'A small metal plug that connects the first wiring level down to a source, drain or gate.' },
  margin: { term: 'Margin', def: 'Extra space the designer leaves around a contact so ordinary misalignment cannot make it touch the wrong thing.' },
  mol: { term: 'MOL', def: 'Middle-of-line: the contacts that link the transistors (front end) to the wiring (back end).' },
  damascene: { term: 'Damascene', def: 'Inlaying metal: etch grooves into insulator, overfill with metal, then polish the excess away.' },
  interconnect: { term: 'Interconnect', def: 'The metal wiring that joins transistors into circuits.' },
  via: { term: 'Via', def: 'A vertical metal plug that joins one wiring level to the next.' },
  beol: { term: 'BEOL', def: 'Back-end-of-line: the stacked levels of metal wiring built above the transistors.' },
  passivation: { term: 'Passivation', def: 'A tough top coat that seals the chip, with openings only over the bond pads.' },
  probe: { term: 'Probe', def: 'Testing each die on the wafer by touching its pads with fine needles on a probe card.' },
  yield: { term: 'Yield', def: 'The share of dies that pass test. In this simulation it is a toy number, not a prediction.' },
  iddq: { term: 'IDDQ', def: 'The current a chip draws when idle. Too much means something is leaking, even if the logic works.' },
  dicing: { term: 'Dicing', def: 'Cutting the wafer into individual dies along the scribe streets, with a thin saw blade or a laser.' },
  dieattach: { term: 'Die attach', def: 'Bonding a die onto its package base with adhesive or solder.' },
  wirebond: { term: 'Wire bond', def: 'A very fine wire welded from a die pad to a package lead.' },
  inverter: { term: 'Inverter', def: 'The simplest logic gate: its output is the opposite of its input. Built here from one PMOS and one NMOS transistor.' },
};

export type TermId = keyof typeof GLOSSARY;
